# fly.toml app configuration file generated for identity-optim-boo on 2023-11-14T15:26:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "identity-optim-boo"
primary_region = "den"

[build]

[[services]]
  internal_port = 5001
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 5001
