# fly.toml app configuration file generated for identity-optim-boo on 2023-11-21T10:09:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "identity-optim-boo"
primary_region = "den"

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
